### PR TITLE
updating to netcore3.1

### PR DESCRIPTION
**Pull request by codemillmatt**
Updating this sample as part of freshness review of Swagger learn module

### CODE REVIEW

**Comment by codemillmatt** [comment]
@nickwalkmsft - fyi

**Comment by nickwalkmsft** [comment]
Awesome. Keep in mind if you've got breaking changes with the current content, you'll need to coordinate this merge with the new content going live; just remind me that this is part of the overall update and I'll help with that.

**Comment by codemillmatt** [comment]
Not only is it breaking content - we'll want to wait on this and the learn module until the sandbox gets more disk space.

I'd imagine later in the week of March 1.

**Comment by nickwalkmsft** [comment]
Did you see Mark's email? The fix is in place, `~` now has 5Gb.

**Comment by codemillmatt** [comment]
Oh nice  - just ran through the current exercise ... the NuGets restore now! So we should be good to go once the build process picks up the docs & Brady gives the thumbs up.

**Comment by codemillmatt** [comment]
@nickwalkmsft  - the learn module was just merged in - can you merge this one too please?

**Pull request merged**
